services:
  backend:
    build: ./backend
    expose:
      - "8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    expose:
      - "80"

  caddy:
    image: caddy:2-alpine
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
